### ISSUE TITLE
Dart Sass Checksum Incorrect

### ISSUE THREAD

**Issue by allenwyma** [sass/homebrew-sass#43] opened 2022-11-04 01:30 UTC
sha256 seems to be wrong for 1.56.0. I tried downloading manually from my own computer and my NAS in another location and I keep getting `077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab` but the formula says it's `1fddc66a11847255434227ab38edc3a0c1dbc53bfa9c3a7bc3393eee142fafbb`

**Comment by rsanheim** [comment] 2022-11-04 01:35
also seeing this, guessing something is borked in the latest version bump?

**Comment by rsanheim** [comment] 2022-11-04 01:41
```
[~/src/monograph/monograph (main)⚡] [130] > brew upgrade sass
==> Upgrading 1 outdated package:
sass/sass/sass 1.55.0 -> 1.56.0
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.4/sdk/dartsdk-macos-arm64-release.zip
Already downloaded: /Users/rsanheim/Library/Caches/Homebrew/downloads/0b16214a3ffb4d7694692cddf89f37a421c570cef102111689fcd7ff7dd92261--dartsdk-macos-arm64-release.zip
==> Downloading https://github.com/sass/dart-sass/archive/1.56.0.tar.gz
Already downloaded: /Users/rsanheim/Library/Caches/Homebrew/downloads/5ed70be2152ac39ed296c68a7aa7edb2010ddfbf5274f2f039ac7223a6e9740b--dart-sass-1.56.0.tar.gz
Error: SHA256 mismatch
Expected: 1fddc66a11847255434227ab38edc3a0c1dbc53bfa9c3a7bc3393eee142fafbb
  Actual: 077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab
    File: /Users/rsanheim/Library/Caches/Homebrew/downloads/5ed70be2152ac39ed296c68a7aa7edb2010ddfbf5274f2f039ac7223a6e9740b--dart-sass-1.56.0.tar.gz
To retry an incomplete download, remove the file above.
```

Downloading the actual tar yields the sha homebrew expects, so either just a mistake in the version in the recipe here or the actual tar has been corrupted:

```
[~/Downloads]> wget https://github.com/sass/dart-sass/archive/1.56.0.tar.gz
--2022-11-03 20:38:28--  https://github.com/sass/dart-sass/archive/1.56.0.tar.gz
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/sass/dart-sass/tar.gz/refs/tags/1.56.0 [following]
--2022-11-03 20:38:29--  https://codeload.github.com/sass/dart-sass/tar.gz/refs/tags/1.56.0
Resolving codeload.github.com (codeload.github.com)... 140.82.112.9
Connecting to codeload.github.com (codeload.github.com)|140.82.112.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 410034 (400K) [application/x-gzip]
Saving to: ‘1.56.0.tar.gz’

1.56.0.tar.gz                                100%[=============================================================================================>] 400.42K  --.-KB/s    in 0.1s

2022-11-03 20:38:29 (2.84 MB/s) - ‘1.56.0.tar.gz’ saved [410034/410034]

[~/Downloads]> sha256sum 1.56.0.tar.gz
077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab  1.56.0.tar.gz
[~/Downloads]>
```

**Comment by steinmb** [comment] 2022-11-07 18:51
Also seeing this.

```
==> Upgrading 1 outdated package:
sass/sass/sass 1.55.0 -> 1.56.0
==> Downloading https://github.com/sass/dart-sass/archive/1.56.0.tar.gz
==> Downloading from https://codeload.github.com/sass/dart-sass/tar.gz/refs/tags/1.56.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 1fddc66a11847255434227ab38edc3a0c1dbc53bfa9c3a7bc3393eee142fafbb
  Actual: 077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab
    File: /Users/steinmb/Library/Caches/Homebrew/downloads/5ed70be2152ac39ed296c68a7aa7edb2010ddfbf5274f2f039ac7223a6e9740b--dart-sass-1.56.0.tar.gz
To retry an incomplete download, remove the file above.


rm /Users/steinmb/Library/Caches/Homebrew/downloads/5ed70be2152ac39ed296c68a7aa7edb2010ddfbf5274f2f039ac7223a6e9740b--dart-sass-1.56.0.tar.gz


brew upgrade sass/sass/sass

==> Upgrading 1 outdated package:
sass/sass/sass 1.55.0 -> 1.56.0
==> Downloading https://github.com/sass/dart-sass/archive/1.56.0.tar.gz
==> Downloading from https://codeload.github.com/sass/dart-sass/tar.gz/refs/tags/1.56.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 1fddc66a11847255434227ab38edc3a0c1dbc53bfa9c3a7bc3393eee142fafbb
  Actual: 077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab
    File: /Users/steinmb/Library/Caches/Homebrew/downloads/5ed70be2152ac39ed296c68a7aa7edb2010ddfbf5274f2f039ac7223a6e9740b--dart-sass-1.56.0.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by TakWolf** [comment] 2022-11-07 18:57
<img width="566" alt="image" src="https://user-images.githubusercontent.com/6064962/200391982-3285ef7f-c695-4b69-8c4c-f235bf8d3960.png">

**Comment by nex3** [comment] 2022-11-07 22:05
It looks like, for some reason, the source archive generated by `git archive` no longer matches the data served by GitHub in its own tar.gz archive for the repo. I'm trying to figure out exactly what the difference is, but if I can't we may need to resort to downloading the tarball from GitHub itself to determine the hash.

In the meantime, I've merged https://github.com/sass/homebrew-sass/pull/44 which should address the issue in the short term.

**Comment by nex3** [comment] 2022-11-07 22:11
I've confirmed that the tar file is itself identical, it's only the gzip that's now different. Unfortunately, it doesn't seem to cleanly match any of the compression levels of GNU gzip, so it may be some sort of custom gzip library whose exact output we can't reliably reproduce.

**Comment by allenwyma** [comment] 2022-11-08 00:03
Fixed with #44

**Comment by nex3** [comment] 2022-11-08 02:19
Reopening because we need to make sure this doesn't happen again next time we release.

**Comment by jdromero88** [comment] 2022-11-09 05:02
Hello,

I still have the same issue on Linux Mint 20.2 x86_64

```bash
==> Downloading https://github.com/sass/dart-sass/archive/1.56.1.tar.gz
==> Downloading from https://codeload.github.com/sass/dart-sass/tar.gz/refs/tags/1.56.1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: db510624782f6ef87e04bbc05666e8d8cf2bccd53bd18f4c954b80cda2cb9e9a
  Actual: 4c6622eb1ac1fb4047b101dc0232df0acb7fd604409a13198f4d9b02b675bde9
    File: /home/jose/.cache/Homebrew/downloads/ff09d061ebc95d19ee8c15039ffda36de755442aa8f3b373c3d014e864ee6515--dart-sass-1.56.1.tar.gz
To retry an incomplete download, remove the file above.
```

```bash
jose@dev:~$ brew info sass/sass/sass
==> sass/sass/sass: stable 1.56.1
Stylesheet Preprocessor
https://sass-lang.com
/home/linuxbrew/.linuxbrew/Cellar/sass/1.55.0 (7 files, 9.0MB) *
  Built from source on 2022-10-20 at 15:04:54
From: https://github.com/sass/homebrew-sass/blob/HEAD/sass.rb
==> Dependencies
Build: dart-lang/dart/dart ✔
Required: gcc ✔, glibc ✔

```

**Comment by markjanzer** [comment] 2022-11-09 05:51
It looks like we're running into the same SHA mismatch for the newest version bump to`1.56.1`. I think we should re-open the issue 😢

**Comment by allenwyma** [comment] 2022-11-09 07:14
yes, can confirm. 😢

**Comment by quimic** [comment] 2022-11-09 07:23
> It looks like we're running into the same SHA mismatch for the newest version bump to`1.56.1`. I think we should re-open the issue 😢

Indeed, I agree that this is issue needs to be re-opened.

**Comment by jbk2** [comment] 2022-11-09 09:19
Experiencing same SHE 256 mismatch issue also (trying to upgrade from 1.45.0 to 1.56.1). Have `brew pin sass`'ed for now.

**Comment by nex3** [comment] 2022-11-09 21:45
Fixed with https://github.com/sass/homebrew-sass/pull/46 in the short term, fixed in the long term by actually releasing the version of `cli_pkg` that knows how to deploy this correctly :skull:.

**Closed by nex3** 2022-11-09 21:45 UTC
