### ISSUE TITLE
Fresh install fails on Monterey 12.2.1

### ISSUE THREAD

**Issue by eldang** [sass/homebrew-sass#41] opened 2022-03-31 23:50 UTC
I'm unable to install Sass through Homebrew, because I get the following message:

```
$ brew install sass/sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.49.10.tar.gz
Already downloaded: /Users/eldan/Library/Caches/Homebrew/downloads/9f06088f6c6b77fb5a65613fd3c7c4954681f8afdf5ea6998b8d4ddec307c76c--dart-sass-1.49.10.tar.gz
==> Installing sass from sass/sass
==> /usr/local/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/eldan/Library/Logs/Homebrew/sass/01.dart:
2022-03-31 23:46:28 +0000

/usr/local/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
Because sass depends on cli_pkg ^2.1.0 which doesn't match any versions, version solving failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues
```

I didn't have Dart installed prior to today - it was installed as a prerequisite on a previous attempt at installing Sass (which is also what downloaded https://github.com/sass/dart-sass/archive/1.49.10.tar.gz ).

I've run `brew update` and `brew doctor`, and `brew config` gets me:

```
$ brew config
HOMEBREW_VERSION: 3.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5f5af43244eaece1f09d695603e1a261676713a0
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f1baa40da4853c8b928a1b6e19c71b1adaf6eaf6
Core tap last commit: 43 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.oU2HWMLvSb/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-x86_64
CLT: 13.3.0.0.1.1645755326
Xcode: 13.3
```

I'm afraid I'm not familiar with Dart or its tooling, so don't know what else I should try.

**Comment by rakeshsubrahmanyam** [comment] 2022-04-01 04:52
I have also faced the same issue

**Comment by bobbyshaw** [comment] 2022-04-01 08:02
I had the same issue. It looks like it depends on `cli_pkg` version `2.1` but this version was retracted https://pub.dev/packages/cli_pkg/versions/2.1.0

**Comment by diogofigueiredo** [comment] 2022-04-01 09:07
I hade the same issue!

**Comment by Sarrus** [comment] 2022-04-01 10:36
I'm getting this as well.

**Comment by griffiti** [comment] 2022-04-01 14:43
I'm also getting the same issue. macOS 12.2

**Comment by mcnishthomas** [comment] 2022-04-01 14:53
Yes, same problem for me, but I'm on Monterey 12.3.1.

**Comment by farbodVand** [comment] 2022-04-01 15:02
Same exact error.

**Comment by aidenguinnip** [comment] 2022-04-01 15:33
Same issue for me.

**Comment by apowell656** [comment] 2022-04-01 16:12
+1 Same issue on 12.3.1

**Comment by doubleforte** [comment] 2022-04-01 16:50
+1 for me.

**Comment by JanMalte** [comment] 2022-04-01 19:56
Duplicate of #40

**Comment by JanMalte** [comment] 2022-04-02 20:10
Please try again with version 1.49.11 released 2. Apr. 2022, 00:46 MESZ
Seems to fix the/most issues

**Comment by eldang** [comment] 2022-04-03 00:37
@JanMalte 1.49.11 fixes it for me on OS X 12.3.1, which I also upgraded since filing the initial issue.  Thank you!

Should we close this issue or wait to hear from someone still using OS X 12.2?

**Comment by doubleforte** [comment] 2022-04-03 03:11
Works great now. Thanks!

**Comment by shoesforindustry** [comment] 2022-04-03 08:08
Thanls fixed for me

**Comment by Sarrus** [comment] 2022-04-04 10:59
Thanks! I'm on MacOS 13.3.1 and it's now working again.

**Comment by griffiti** [comment] 2022-04-04 14:58
Works great now. Thanks for getting that fix out so quickly!

**Comment by aidenguinnip** [comment] 2022-04-04 16:14
It is fixed for me as well!

**Closed** 2022-04-06 00:53 UTC
